{% set name = "dowhy" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8812d54a40e33732a8bf72d7d1633219de2942e3f08006bcad992ff077b0640b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - networkx >=2.0
    - numpy >=1.15
    - pandas >=0.24
    - pydot >=1.4
    - python >=3.5
    - scikit-learn
    - scipy
    - statsmodels
    - sympy >=1.4

test:
  imports:
    - dowhy
    - dowhy.api
    - dowhy.causal_estimators
    - dowhy.causal_refuters
    - dowhy.do_samplers

about:
  home: https://github.com/microsoft/dowhy
  license: MIT
  license_family: MIT
  license_file: LICENSE  # LICENSE file is in the root folder of the archive
  summary: DoWhy is a Python library for causal inference that supports explicit modeling and testing of causal assumptions.
  doc_url: https://microsoft.github.io/dowhy/
  dev_url: https://github.com/microsoft/dowhy

extra:
  recipe-maintainers:
    - amit-sharma
